### ISSUE TITLE
Python script stops (maybe encoding problem?)

### ISSUE THREAD

**Issue by iyereed** [robwebset/script.audiobooks#1]
When I try to launch AudioBooks, it doesn't. That's a useful part of the log (I guess):
```
09:53:05 T:140244350523136   DEBUG: script.audiobooks: AudioBooksDB: Get book details for /home/ya/Музыка/Аудиокниги/Дмитрий Глуховский - Метро 2035 (Дмитрий Креминский)
09:53:05 T:140244350523136   DEBUG: script.audiobooks: AudioBooksDB: Database info: (4, '/home/ya/\xd0\x9c\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0/\xd0\x90\xd1\x83\xd0\xb4\xd0\xb8\xd0\xbe\xd0\xba\xd0\xbd\xd0\xb8\xd0\xb3\xd0\xb8/\xd0\x94\xd0\xbc\xd0\xb8\xd1\x82\xd1\x80\xd0\xb8\xd0\xb9 \xd0\x93\xd0\xbb\xd1\x83\xd1\x85\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 - \xd0\x9c\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe 2035 (\xd0\x94\xd0\xbc\xd0\xb8\xd1\x82\xd1\x80\xd0\xb8\xd0\xb9 \xd0\x9a\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9)', '\xd0\x94\xd0\xbc\xd0\xb8\xd1\x82\xd1\x80\xd0\xb8\xd0\xb9 \xd0\x93\xd0\xbb\xd1\x83\xd1\x85\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 - \xd0\x9c\xd0\xb5\xd1\x82\xd1\x80\xd0\xbe 2035 (\xd0\x94\xd0\xbc\xd0\xb8\xd1\x82\xd1\x80\xd0\xb8\xd0\xb9 \xd0\x9a\xd1\x80\xd0\xb5\xd0\xbc\xd0\xb8\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9)', 24, 0, 0, 0)
09:53:05 T:140244350523136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xd0 in position 35: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/ya/.kodi/addons/script.audiobooks/plugin.py", line 323, in <module>
                                                menuNav.showAudiobooks()
                                              File "/home/ya/.kodi/addons/script.audiobooks/plugin.py", line 129, in showAudiobooks
                                                log("AudioBooksPlugin: Display title is %s for %s" % (displayString, audioBookFile))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 35: ordinal not in range(128)
                                            -->End of Python script error report<--
09:53:05 T:140245705107968   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
09:53:05 T:140245705107968   DEBUG: Window DialogKaiToast.xml was already loaded
09:53:05 T:140245705107968   DEBUG: Alloc resources: 0.00ms
09:53:05 T:140245022914304    INFO: CActiveAESink::OpenSink - initialize sink
09:53:05 T:140245022914304   DEBUG: CActiveAESink::OpenSink - trying to open device PULSE:Default
09:53:05 T:140244350523136    INFO: Python script stopped
09:53:05 T:140244350523136   DEBUG: Thread LanguageInvoker 140244350523136 terminating
09:53:05 T:140245022914304   DEBUG: PulseAudio: Context authorizing
09:53:05 T:140245022914304   DEBUG: PulseAudio: Context setting name
09:53:05 T:140245022914304   DEBUG: PulseAudio: Context ready
09:53:05 T:140245022914304   DEBUG: PulseAudio: Stream ready
09:53:05 T:140245022914304  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
09:53:05 T:140244333737728   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
09:53:05 T:140245705107968   ERROR: GetDirectory - Error getting plugin://script.audiobooks/
09:53:05 T:140245022914304   DEBUG: CActiveAESink::OpenSink - PULSE Initialized:
09:53:05 T:140245022914304   DEBUG:   Output Device : Default
09:53:05 T:140245022914304   DEBUG:   Sample Rate   : 44100
09:53:05 T:140245022914304   DEBUG:   Sample Format : AE_FMT_FLOAT
09:53:05 T:140245022914304   DEBUG:   Channel Count : 2
09:53:05 T:140245022914304   DEBUG:   Channel Layout: FL,FR
09:53:05 T:140245022914304   DEBUG:   Frames        : 2205
09:53:05 T:140245022914304   DEBUG:   Frame Samples : 4410
09:53:05 T:140245022914304   DEBUG:   Frame Size    : 8
09:53:05 T:140245705107968   ERROR: CGUIMediaWindow::GetDirectory(plugin://script.audiobooks/) failed
09:53:05 T:140245705107968   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/audio)
09:53:05 T:140245705107968   DEBUG:   ParentPath = []
09:53:05 T:140244350523136  NOTICE: Thread BackgroundLoader start, auto delete: false
09:53:05 T:140244350523136   DEBUG: Loading items: 2, directory: addons://sources/audio sort method: 0, ascending: false
09:53:05 T:140244350523136   DEBUG: Saving fileitems [addons://sources/audio]
09:53:05 T:140244350523136   DEBUG:   -- items: 2, sort method: 0, ascending: false
09:53:05 T:140244350523136   DEBUG: Thread BackgroundLoader 140244350523136 terminating
09:53:05 T:140245705107968   DEBUG: RetrieveMusicInfo() took 9 msec
09:53:05 T:140244350523136  NOTICE: Thread BackgroundLoader start, auto delete: false
09:53:05 T:140244350523136   DEBUG: Thread BackgroundLoader 140244350523136 terminating
09:53:05 T:140245705107968   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
09:53:07 T:140245705107968   DEBUG: ------ Window Init (Pointer.xml) ------
09:53:08 T:140245705107968   DEBUG: Keyboard: scancode: 0x40, sym: 0x0134, unicode: 0x0000, modifier: 0x100
09:53:08 T:140245705107968   DEBUG: OnKey: alt-leftalt (0x4f0d4) pressed, action is
09:53:08 T:140245705107968   DEBUG: ------ Window Deinit (Pointer.xml) ------
09:53:10 T:140245705107968   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
09:53:15 T:140245705107968    INFO: Python, unloading python shared library because no scripts are running anymore
09:53:15 T:140245705107968   DEBUG: UnloadExtensionLibs, clearing python extension libraries
09:53:35 T:140244333737728   DEBUG: Thread JobWorker 140244333737728 terminating (autodelete)
09:53:35 T:140244383901440   DEBUG: Thread JobWorker 140244383901440 terminating (autodelete)
09:53:41 T:140245705107968   DEBUG: Keyboard: scancode: 0x40, sym: 0x0134, unicode: 0x0000, modifier: 0x100
09:53:41 T:140245705107968   DEBUG: OnKey: alt-leftalt (0x4f0d4) pressed, action is
```

**Comment by robwebset** [comment]
Please can you post issues to the forum:

http://forum.kodi.tv/showthread.php?tid=239859

This was already reported on there and a patched version for this specific issue is available. (Although there are still likely other encoding issues that I have not hit or solved yet)

Thanks
Rob
